FROM node:20.11-slim

# Create app directory
WORKDIR /app

# copy package.json and package-lock.json
COPY package*.json ./
RUN npm install

# Copy app source code
COPY . .

# Install app dependencies
RUN npm run build

# set environment variables
ARG BACKEND_PORT=3001
ENV PORT=${BACKEND_PORT}

ARG TFIDF_WORKER_NUM
ARG TFIDF_WORKER_BATCH_SIZE
ARG MIGRATION_WORKER_NUM
ARG TFIDF_CACHE_TTL
ARG DEFAULT_CACHE_TTL
ARG DATABASE_URL
ENV TFIDF_WORKER_NUM=${TFIDF_WORKER_NUM}
ENV TFIDF_WORKER_BATCH_SIZE=${TFIDF_WORKER_BATCH_SIZE}
ENV MIGRATION_WORKER_NUM=${MIGRATION_WORKER_NUM}
ENV TFIDF_CACHE_TTL=${TFIDF_CACHE_TTL}
ENV DEFAULT_CACHE_TTL=${DEFAULT_CACHE_TTL}
ENV DATABASE_URL=${DATABASE_URL}


VOLUME /app/.env

# Expose port and start application
EXPOSE $PORT
CMD ["npm", "run", "start:prod"]
